package codegen

import (
	"bytes"
	"fmt"
	"text/template"
)

// Generator produces Go source code from an inferred schema.
type Generator struct {
	PkgName          string
	SchemaName       string // e.g. "Checkout" from "checkout.umpire.json"
	FieldsName       string
	ConditionsName   string
	AvailabilityName string
	Inferred         *InferredSchema
}

// GenerateResult holds the generated Go source code.
type GenerateResult struct {
	Source string
}

// NewGenerator creates a Generator for the given schema and config.
func NewGenerator(schemaName, pkgName, fieldsName, conditionsName string, inferred *InferredSchema) *Generator {
	return &Generator{
		PkgName:          pkgName,
		SchemaName:       schemaName,
		FieldsName:       fieldsName,
		ConditionsName:   conditionsName,
		AvailabilityName: schemaName + "Availability",
		Inferred:         inferred,
	}
}

// Generate produces the full Go source file.
func (g *Generator) Generate() (*GenerateResult, error) {
	var buf bytes.Buffer

	// Group branches by group name
	branchGroups := make(map[string][]OneOfBranch)
	for _, b := range g.Inferred.Branches {
		branchGroups[b.GroupName] = append(branchGroups[b.GroupName], b)
	}

	tmpl := template.Must(template.New("umpire").Funcs(templateFuncMap).Parse(templateSrc))

	data := generationTemplateData{
		PkgName:          g.PkgName,
		SchemaName:       g.SchemaName,
		FieldsName:       g.FieldsName,
		ConditionsName:   g.ConditionsName,
		AvailabilityName: g.AvailabilityName,
		Fields:           g.Inferred.Fields,
		Conditions:       g.Inferred.Conditions,
		Branches:         g.Inferred.Branches,
		BranchGroups:     branchGroups,
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	return &GenerateResult{Source: buf.String()}, nil
}

// generationTemplateData is the data passed to the Go template.
type generationTemplateData struct {
	PkgName          string
	SchemaName       string
	FieldsName       string
	ConditionsName   string
	AvailabilityName string
	Fields           []FieldTypeInfo
	Conditions       []ConditionTypeInfo
	Branches         []OneOfBranch
	// BranchGroups groups branches by their GroupName for template rendering.
	BranchGroups map[string][]OneOfBranch
}

// templateFuncMap provides helper functions for the template.
var templateFuncMap = template.FuncMap{
	"goType": func(ft FieldTypeInfo) string {
		return string(ft.GoType)
	},
	"condGoType": func(ct ConditionTypeInfo) string {
		return string(ct.GoType)
	},
	"goFieldName": func(name string) string {
		return GoFieldName(name)
	},
	"goFieldNameFT": func(ft FieldTypeInfo) string {
		return GoFieldName(ft.Name)
	},
}

// templateSrc is the Go source template.
const templateSrc = `// Code generated by umpire-gen; DO NOT EDIT.

package {{ .PkgName }}

// {{ .FieldsName }} holds the fields for {{ .SchemaName }} availability checks.
type {{ .FieldsName }} struct {
{{- range .Fields }}
	{{ goFieldNameFT . }} {{ goType . }} ` + "`json:\"{{ .JSONTag }},omitempty\"`" + `
{{- end }}
}

// {{ .ConditionsName }} holds the conditions for {{ .SchemaName }} availability checks.
type {{ .ConditionsName }} struct {
{{- range .Conditions }}
	{{ .Name }} {{ condGoType . }} ` + "`json:\"{{ .JSONTag }}\"`" + `
{{- end }}
}

// {{ .AvailabilityName }} holds the availability status for each field.
type {{ .AvailabilityName }} struct {
{{- range .Fields }}
	{{ goFieldNameFT . }} FieldStatus
{{- end }}
{{- range .Branches }}
	Active{{ .Branch }} {{ .GroupName }}
{{- end }}
}

// FieldStatus mirrors the conformance expectedAvailability shape exactly.
// Valid and Error are only populated when a named validator is attached
// to the field and the field is currently enabled and satisfied.
type FieldStatus struct {
	Enabled   bool
	Required  bool
	Satisfied bool
	Fair      bool
	Reason    *string  // nil when enabled; first blocking reason otherwise
	Reasons   []string // all blocking reasons; empty slice when enabled
	Valid     *bool    // nil = no validator; non-nil = validation result
	Error     string   // non-empty only when Valid != nil && !*Valid
}

{{- range $groupName, $branchList := .BranchGroups }}
// {{ $groupName }} represents the active branch of the {{ $groupName }} oneOf/eitherOf group.
type {{ $groupName }} int

const (
	{{ $groupName }}None {{ $groupName }} = iota
{{- range $branchList }}
	{{ .Branch }} {{ $groupName }}
{{- end }}
)
{{- end }}
`
