package umpiregen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"sort"
	"strings"

	"github.com/umpire-tools/umpire-go-gen/pkg/codegen"
	"github.com/umpire-tools/umpire-go-gen/pkg/schema"
	"github.com/umpire-tools/umpire-go-gen/pkg/structgen"
)

// generateStructural combines value-schema types with availability functions.
// Check and Challenge use the richer root field types.
// Inputs without a value schema retain the existing availability-only output.
func generateStructural(umpireJSON, valueSchemaJSON []byte, cfg Config) (string, error) {
	if src, ok, err := tryStructural(umpireJSON, valueSchemaJSON, cfg); err != nil {
		return "", err
	} else if ok {
		return src, nil
	}
	// The valueSchema could not be mapped to structural types (e.g. it contains
	// an excluded keyword like allOf). Fall back to availability-only output; the
	// profile definition issues are surfaced separately by the caller.
	return generateFromBytes(umpireJSON, cfg)
}

// tryStructural attempts to emit structural + availability merged output. The
// bool reports whether structural mapping succeeded.
func tryStructural(umpireJSON, valueSchemaJSON []byte, cfg Config) (string, bool, error) {
	if len(valueSchemaJSON) == 0 {
		return "", false, nil
	}

	spec, err := structgen.Build(valueSchemaJSON, cfg.SchemaName)
	if err != nil {
		return "", false, nil
	}
	fieldsName := cfg.FieldsName
	if fieldsName == "" {
		fieldsName = cfg.SchemaName + "Fields"
	}
	em, err := structgen.Emit(spec, structgen.EmitOptions{
		PkgName:      cfg.PkgName,
		SchemaName:   cfg.SchemaName,
		RootTypeName: fieldsName,
	})
	if err != nil {
		return "", false, nil
	}

	// Surface structural root types in the availability Fields struct while
	// retaining primitive semantics for named enum emptiness checks.
	overrides := map[string]codegen.GoType{}
	for name, t := range structgen.RootGoTypes(spec) {
		overrides[name] = codegen.GoType(t)
	}
	underlying := map[string]codegen.GoType{}
	for name, t := range structgen.RootUnderlyingGoTypes(spec) {
		underlying[name] = codegen.GoType(t)
	}

	avail, err := generateAvailability(umpireJSON, cfg, overrides, underlying)
	if err != nil {
		return "", false, err
	}

	merged, err := mergePackageFiles(em.Source, avail)
	if err != nil {
		return "", false, err
	}
	return merged, true, nil
}

// generateAvailability mirrors generateFromBytes but honors explicit field-type
// overrides so the availability Fields struct can reference structural types.
func generateAvailability(schemaJSON []byte, cfg Config, overrides, underlying map[string]codegen.GoType) (string, error) {
	s, err := schema.Parse(schemaJSON)
	if err != nil {
		return "", fmt.Errorf("parse schema: %w", err)
	}
	inferred, err := codegen.InferTypes(s)
	if err != nil {
		return "", fmt.Errorf("infer types: %w", err)
	}

	fieldsName := cfg.FieldsName
	if fieldsName == "" {
		fieldsName = cfg.SchemaName + "Fields"
	}
	conditionsName := cfg.ConditionsName
	if conditionsName == "" {
		conditionsName = cfg.SchemaName + "Conditions"
	}

	gen := codegen.NewGenerator(cfg.SchemaName, cfg.PkgName, fieldsName, conditionsName, inferred)
	gen.WithFieldTypeOverrides(overrides)
	gen.WithFieldUnderlyingTypes(underlying)
	gen.WithFields(s.Fields)
	gen.WithRules(s.Rules)
	gen.WithSchema(s)

	result, err := gen.Generate()
	if err != nil {
		return "", fmt.Errorf("generate code: %w", err)
	}
	return result.Source, nil
}

// mergePackageFiles combines two or more Go source files that share a package
// and (possibly) different import blocks into one file with a unioned import
// block. Bodies are concatenated. Each input must use the `import (...)` form.
func mergePackageFiles(sources ...string) (string, error) {
	var pkg string
	var importSet []string
	var bodies []string
	importSeen := make(map[string]bool)
	declarations := make(map[string]bool)

	for _, src := range sources {
		if err := collectTopLevelDeclarations(src, declarations); err != nil {
			return "", err
		}
		p, imports, body, err := splitPackageFile(src)
		if err != nil {
			return "", err
		}
		if pkg == "" {
			pkg = p
		} else if p != pkg {
			return "", fmt.Errorf("cannot merge packages %q and %q", pkg, p)
		}
		for _, imp := range imports {
			if !importSeen[imp] {
				importSeen[imp] = true
				importSet = append(importSet, imp)
			}
		}
		bodies = append(bodies, strings.TrimSpace(body))
	}
	sort.Strings(importSet)

	var b strings.Builder
	b.WriteString("// Code generated by umpire-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	if len(importSet) > 0 {
		b.WriteString("import (\n")
		for _, imp := range importSet {
			fmt.Fprintf(&b, "\t%s\n", imp)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(strings.Join(bodies, "\n\n"))
	return b.String(), nil
}

// collectTopLevelDeclarations rejects names that would be redeclared after the
// generated files are merged. Structural and availability sources independently
// use schema-derived names, so an invalid profile can otherwise produce source
// that parses but cannot compile.
func collectTopLevelDeclarations(src string, seen map[string]bool) error {
	file, err := parser.ParseFile(token.NewFileSet(), "generated.go", src, 0)
	if err != nil {
		return fmt.Errorf("parse generated source: %w", err)
	}
	for _, decl := range file.Decls {
		var names []*ast.Ident
		switch decl := decl.(type) {
		case *ast.FuncDecl:
			if decl.Recv == nil {
				names = append(names, decl.Name)
			}
		case *ast.GenDecl:
			for _, spec := range decl.Specs {
				switch spec := spec.(type) {
				case *ast.TypeSpec:
					names = append(names, spec.Name)
				case *ast.ValueSpec:
					names = append(names, spec.Names...)
				}
			}
		}
		for _, name := range names {
			if seen[name.Name] {
				return fmt.Errorf("cannot merge duplicate declaration %q", name.Name)
			}
			seen[name.Name] = true
		}
	}
	return nil
}

// splitPackageFile splits a generated Go source into package name, its import
// block entries, and the remaining body. Only the `import (...)` form is handled.
func splitPackageFile(src string) (pkg string, imports []string, body string, err error) {
	lines := strings.Split(src, "\n")
	pkgLine := -1
	for i, ln := range lines {
		if strings.HasPrefix(strings.TrimSpace(ln), "package ") {
			pkgLine = i
			pkg = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(ln), "package "))
			break
		}
	}
	if pkgLine == -1 {
		return "", nil, "", fmt.Errorf("no package clause found")
	}

	importStart := -1
	for i, ln := range lines {
		if strings.TrimSpace(ln) == "import (" && i > pkgLine {
			importStart = i
			break
		}
	}
	if importStart == -1 {
		// No import block: body begins right after the package line.
		body = strings.Join(lines[pkgLine+1:], "\n")
		return pkg, nil, body, nil
	}

	for i := importStart + 1; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if t == ")" {
			body = strings.Join(lines[i+1:], "\n")
			return pkg, imports, body, nil
		}
		if t != "" {
			imports = append(imports, strings.TrimSpace(lines[i]))
		}
	}
	return "", nil, "", fmt.Errorf("unterminated import block")
}
