package structgen

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/umpire-tools/umpire-go-gen/pkg/codegen"
)

// Emission is the rendered Go source for a Spec.
type Emission struct {
	Source string
}

// EmitOptions configures structural emission.
type EmitOptions struct {
	PkgName      string // Go package name for the generated source
	SchemaName   string // camelCase/Pascal Go symbol prefix for the public raw API
	RootTypeName string // Go type that Decode<Schema> decodes into (e.g. <Schema>Fields)
}

// Emit writes a complete Go source file that uses only the standard library.
// It emits strict object decoders, enums, tagged unions, and typed validation.
// It also emits Validate<Schema>JSON, Decode<Schema>, and structural issue types.
// Profile-declared objects, unions, and enums never expose `any`.
func Emit(spec *Spec, opts EmitOptions) (*Emission, error) {
	utf8 := specNeedsImports(spec)
	schemaPrefix := opts.SchemaName
	if schemaPrefix == "" {
		schemaPrefix = spec.RootName
	}

	var b strings.Builder
	b.WriteString("// Code generated by umpire-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.PkgName)
	emitImports(&b, utf8)

	// Plan-conformant raw validation + public API (Validate/Decode/StructuralIssue).
	emitStructural(&b, spec, opts)

	// Root object (with strict decode) + Validate().
	rootTD := TypeDef{Name: spec.RootName, Fields: spec.Root, Kind: KindObject}
	emitStruct(&b, spec.RootName, spec.Root)
	emitStrictDecode(&b, rootTD, schemaPrefix)
	emitValidation(&b, spec)

	// Definition aliases, enums, objects, then branch-specific unions.
	for _, td := range spec.Types {
		if td.AliasRef != "" {
			fmt.Fprintf(&b, "type %s = %s\n\n", td.Name, td.AliasRef)
		}
	}
	for _, td := range spec.Types {
		if td.AliasRef != "" {
			continue
		}
		switch td.Kind {
		case KindScalar:
			fmt.Fprintf(&b, "type %s %s\n\n", td.Name, scalarGoType(td.Scalar))
		case KindArray:
			fmt.Fprintf(&b, "type %s []%s\n\n", td.Name, baseGoType(*td.Elem))
		case KindEnum:
			emitEnum(&b, td)
		}
	}
	for _, td := range spec.Types {
		if td.AliasRef == "" && td.Kind == KindObject {
			emitStruct(&b, td.Name, td.Fields)
			emitStrictDecode(&b, td, schemaPrefix)
		}
	}
	for _, td := range spec.Types {
		if td.AliasRef == "" && td.Kind == KindUnion {
			emitUnionDecoder(&b, spec, td, schemaPrefix)
		}
	}

	return &Emission{Source: b.String()}, nil
}

func emitImports(b *strings.Builder, utf8 bool) {
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"math/big\"\n")
	b.WriteString("\t\"strconv\"\n") // raw validator integer exponent / array index paths
	b.WriteString("\t\"strings\"\n") // escapePtr + int parsing
	b.WriteString("\t\"sort\"\n")    // structural issue normalization
	if utf8 {
		b.WriteString("\t\"unicode/utf8\"\n")
	}
	b.WriteString(")\n\n")
}

// specNeedsImports reports whether utf8 (string code-point lengths) is required
// by the generated code. strconv, strings and sort are always emitted because
// the raw structural validator uses them unconditionally.
func specNeedsImports(spec *Spec) (utf8 bool) {
	var walkType func(FieldType)
	walkType = func(ft FieldType) {
		if (ft.Kind == KindScalar || ft.Kind == KindEnum) && ft.Scalar == ScalarString && (ft.Constraints.MinLength != nil || ft.Constraints.MaxLength != nil) {
			utf8 = true
		}
		if ft.Kind == KindArray && ft.Elem != nil {
			walkType(*ft.Elem)
		}
	}
	walk := func(fields []FieldDef) {
		for _, f := range fields {
			walkType(f.Type)
			if (f.Type.Kind == KindScalar || f.Type.Kind == KindEnum) && f.Type.Scalar == ScalarString && (f.MinLength != nil || f.MaxLength != nil) {
				utf8 = true
			}
		}
	}
	walk(spec.Root)
	for _, td := range spec.Types {
		walk(td.Fields)
		for _, br := range td.Branches {
			walk(br.Fields)
		}
	}
	return
}

// RootGoTypes maps each original root property name to its Go type.
// Every profile root field uses a pointer to preserve presence.
// Nil records omission as distinct from an explicit value for Umpire evaluation.
func RootGoTypes(spec *Spec) map[string]string {
	out := make(map[string]string, len(spec.Root))
	for _, f := range spec.Root {
		out[f.Name] = "*" + baseGoType(f.Type)
	}
	return out
}

// RootUnderlyingGoTypes maps root enum fields to the scalar type used for
// availability emptiness semantics. Ordinary scalar overrides already carry
// their own semantics; only named enum types need this side channel.
func RootUnderlyingGoTypes(spec *Spec) map[string]string {
	out := make(map[string]string)
	for _, f := range spec.Root {
		switch f.Type.Kind {
		case KindEnum, KindScalar:
			if f.Type.Ref != "" {
				out[f.Name] = scalarGoType(f.Type.Scalar)
			}
		case KindArray:
			if f.Type.Elem != nil {
				out[f.Name] = "[]" + baseGoType(*f.Type.Elem)
			}
		}
	}
	return out
}

// baseGoType renders the non-nullable Go type string for a field type.
func baseGoType(ft FieldType) string {
	if ft.Ref != "" {
		return ft.Ref
	}
	switch ft.Kind {
	case KindScalar:
		switch ft.Scalar {
		case ScalarString:
			return "string"
		case ScalarBool:
			return "bool"
		case ScalarInt:
			return "int64"
		case ScalarNumber:
			return "float64"
		}
	case KindArray:
		return "[]" + baseGoType(*ft.Elem)
	case KindObject, KindEnum, KindUnion:
		return ft.Ref
	}
	return "string"
}

// fieldGoType renders the nullable Go type for a field, honoring requiredness.
func fieldGoType(fd FieldDef) string {
	base := baseGoType(fd.Type)
	if fd.Required {
		return base
	}
	switch fd.Type.Kind {
	case KindScalar, KindObject, KindEnum, KindUnion:
		return "*" + base
	case KindArray:
		return "*" + base
	}
	return base
}

// goJSONTag renders the struct tag for a field.
func goJSONTag(fd FieldDef) string {
	tag := fd.JSONTag
	if !fd.Required {
		tag += ",omitempty"
	}
	return tag
}

func emitStruct(b *strings.Builder, name string, fields []FieldDef) {
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, fd := range fields {
		fmt.Fprintf(b, "\t%s %s %q\n", fd.GoName, fieldGoType(fd), "json:"+strconv.Quote(goJSONTag(fd)))
	}
	b.WriteString("}\n\n")
}

func emitEnum(b *strings.Builder, td TypeDef) {
	fmt.Fprintf(b, "type %s %s\n\n", td.Name, scalarGoType(td.Scalar))
	b.WriteString("const (\n")
	for _, v := range td.Values {
		fmt.Fprintf(b, "\t%s%s %s = %s\n", td.Name, v.Name, td.Name, enumWireLiteral(v.Wire))
	}
	b.WriteString(")\n\n")
}

func scalarGoType(scalar Scalar) string {
	switch scalar {
	case ScalarBool:
		return "bool"
	case ScalarInt:
		return "int64"
	case ScalarNumber:
		return "float64"
	default:
		return "string"
	}
}

func enumWireLiteral(value any) string {
	switch value := value.(type) {
	case string:
		return fmt.Sprintf("%q", value)
	case bool:
		return fmt.Sprintf("%t", value)
	case int64:
		return fmt.Sprintf("%d", value)
	case float64:
		return fmt.Sprintf("%v", value)
	default:
		return "0"
	}
}

// emitUnionDecoder renders a strict discriminator-based UnmarshalJSON for a union.
func emitUnionDecoder(b *strings.Builder, _ *Spec, td TypeDef, schemaPrefix string) {
	discJSON := td.Discriminator
	enumName := td.Name + "Kind"
	interfaceName := td.Name + "Value"

	fmt.Fprintf(b, "// %s is the sealed branch value for %s.\n", interfaceName, td.Name)
	fmt.Fprintf(b, "type %s interface { is%s() }\n\n", interfaceName, interfaceName)
	fmt.Fprintf(b, "type %s struct {\n\tValue %s `json:\"-\"`\n}\n\n", td.Name, interfaceName)
	for _, br := range td.Branches {
		variant := interfaceName + codegen.GoFieldName(br.Wire)
		emitStruct(b, variant, br.Fields)
		fmt.Fprintf(b, "func (*%s) is%s() {}\n\n", variant, interfaceName)
		emitStrictDecode(b, TypeDef{Name: variant, Kind: KindObject, Fields: br.Fields}, schemaPrefix)
	}

	fmt.Fprintf(b, "// UnmarshalJSON decodes %s by its %q discriminator const.\n", td.Name, discJSON)
	fmt.Fprintf(b, "func (u *%s) UnmarshalJSON(data []byte) error {\n", td.Name)
	b.WriteString("\tvar raw map[string]json.RawMessage\n")
	b.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\tdvRaw, ok := raw[%q]\n", discJSON)
	b.WriteString("\tif !ok {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q)\n", "missing discriminator field "+discJSON)
	b.WriteString("\t}\n")
	b.WriteString("\tvar dv string\n")
	b.WriteString("\tif err := json.Unmarshal(dvRaw, &dv); err != nil {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q, err)\n", "discriminator "+discJSON+" is not a string: %v")
	b.WriteString("\t}\n")
	// Dispatch into a branch-specific concrete type. Same-wire fields in other
	// branches never share storage and may therefore use incompatible Go types.
	fmt.Fprintf(b, "\tswitch %s(dv) {\n", enumName)
	for _, br := range td.Branches {
		variant := interfaceName + codegen.GoFieldName(br.Wire)
		fmt.Fprintf(b, "\tcase %s%s:\n", enumName, codegen.GoFieldName(br.Wire))
		fmt.Fprintf(b, "\t\tvar next %s\n", variant)
		b.WriteString("\t\tif err := json.Unmarshal(data, &next); err != nil { return err }\n")
		b.WriteString("\t\tu.Value = &next\n\t\treturn nil\n")
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q, dv)\n", "unknown discriminator "+discJSON+": %q")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func (u %s) MarshalJSON() ([]byte, error) {\n", td.Name)
	fmt.Fprintf(b, "\tif u.Value == nil { return nil, fmt.Errorf(%q) }\n", "cannot marshal zero "+td.Name+": no union branch selected")
	b.WriteString("\tswitch branch := u.Value.(type) {\n")
	for _, br := range td.Branches {
		variant := interfaceName + codegen.GoFieldName(br.Wire)
		fmt.Fprintf(b, "\tcase *%s:\n", variant)
		fmt.Fprintf(b, "\t\tif branch == nil { return nil, fmt.Errorf(%q) }\n", "cannot marshal "+td.Name+": selected branch is nil")
		b.WriteString("\t\treturn json.Marshal(branch)\n")
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(%q, u.Value)\n", "cannot marshal "+td.Name+": invalid union branch %T")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}
