package structgen

import (
	"fmt"
	"strings"
)

// Emission is the rendered Go source for a Spec.
type Emission struct {
	Source string
}

// Emit renders a Spec into a complete, standard-library-only Go source file.
// Objects become named structs with strict UnmarshalJSON (unknown/trailing/
// required rejection) and validateInto; enums become named types + constants;
// unions carry discriminator-based decoding; the root gains Validate(). Never
// emits `any` for a profile-declared object/union/enum.
func Emit(spec *Spec, pkgName string) (*Emission, error) {
	strconv, utf8 := specNeedsImports(spec)

	var b strings.Builder
	b.WriteString("// Code generated by umpire-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	emitImports(&b, strconv, utf8)

	// Root object (with strict decode) + Validate().
	rootTD := TypeDef{Name: spec.RootName, Fields: spec.Root, Kind: KindObject}
	emitStruct(&b, spec.RootName, spec.Root)
	emitStrictDecode(&b, rootTD)
	emitValidation(&b, spec)

	// Enums, then objects, then unions.
	for _, td := range spec.Types {
		if td.Kind == KindEnum {
			emitEnum(&b, td)
		}
	}
	for _, td := range spec.Types {
		if td.Kind == KindObject {
			emitStruct(&b, td.Name, td.Fields)
			emitStrictDecode(&b, td)
		}
	}
	for _, td := range spec.Types {
		if td.Kind == KindUnion {
			emitStruct(&b, td.Name, td.Fields)
			emitUnionDecoder(&b, spec, td)
		}
	}

	return &Emission{Source: b.String()}, nil
}

func emitImports(b *strings.Builder, strconv, utf8 bool) {
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	if strconv {
		b.WriteString("\t\"strconv\"\n")
	}
	if utf8 {
		b.WriteString("\t\"unicode/utf8\"\n")
	}
	b.WriteString(")\n\n")
}

// specNeedsImports reports whether strconv (array-of-reference index paths) and
// utf8 (string code-point lengths) are required by the generated code.
func specNeedsImports(spec *Spec) (strconv, utf8 bool) {
	walk := func(fields []FieldDef) {
		for _, f := range fields {
			switch f.Type.Kind {
			case KindArray:
				if f.Type.Elem.IsReference() {
					strconv = true
				}
			case KindScalar:
				if f.Type.Scalar == ScalarString && (f.MinLength != nil || f.MaxLength != nil) {
					utf8 = true
				}
			}
		}
	}
	walk(spec.Root)
	for _, td := range spec.Types {
		walk(td.Fields)
	}
	return
}

// RootGoTypes returns the emitted Go field type for each root field, keyed by
// original JSON name. Used by the profile path to surface structural root types
// in the existing availability Fields struct.
func RootGoTypes(spec *Spec) map[string]string {
	out := make(map[string]string, len(spec.Root))
	for _, f := range spec.Root {
		out[f.Name] = fieldGoType(f)
	}
	return out
}

// baseGoType renders the non-nullable Go type string for a field type.
func baseGoType(ft FieldType) string {
	switch ft.Kind {
	case KindScalar:
		switch ft.Scalar {
		case ScalarString:
			return "string"
		case ScalarBool:
			return "bool"
		case ScalarInt:
			return "int"
		case ScalarNumber:
			return "float64"
		}
	case KindArray:
		return "[]" + baseGoType(*ft.Elem)
	case KindObject, KindEnum, KindUnion:
		return ft.Ref
	}
	return "string"
}

// fieldGoType renders the nullable Go type for a field, honoring requiredness.
func fieldGoType(fd FieldDef) string {
	base := baseGoType(fd.Type)
	if fd.Required {
		return base
	}
	switch fd.Type.Kind {
	case KindScalar, KindObject, KindEnum, KindUnion:
		return "*" + base
	case KindArray:
		return base // nil slice already encodes absence
	}
	return base
}

// goJSONTag renders the struct tag for a field.
func goJSONTag(fd FieldDef) string {
	tag := fd.JSONTag
	if !fd.Required {
		tag += ",omitempty"
	}
	return tag
}

func emitStruct(b *strings.Builder, name string, fields []FieldDef) {
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, fd := range fields {
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", fd.GoName, fieldGoType(fd), goJSONTag(fd))
	}
	b.WriteString("}\n\n")
}

func emitEnum(b *strings.Builder, td TypeDef) {
	fmt.Fprintf(b, "type %s string\n\n", td.Name)
	b.WriteString("const (\n")
	for _, v := range td.Values {
		fmt.Fprintf(b, "\t%s%s %s = %q\n", td.Name, v.Name, td.Name, v.Wire)
	}
	b.WriteString(")\n\n")
}

// emitUnionDecoder renders a strict discriminator-based UnmarshalJSON for a union.
func emitUnionDecoder(b *strings.Builder, spec *Spec, td TypeDef) {
	discJSON := wireName(td.Discriminator)
	enumName := td.Name + "Kind"

	fmt.Fprintf(b, "// UnmarshalJSON decodes %s by its %q discriminator const.\n", td.Name, discJSON)
	fmt.Fprintf(b, "func (u *%s) UnmarshalJSON(data []byte) error {\n", td.Name)
	b.WriteString("\tvar raw map[string]json.RawMessage\n")
	b.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\tdvRaw, ok := raw[%q]\n", discJSON)
	b.WriteString("\tif !ok {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q)\n", "missing discriminator field "+discJSON)
	b.WriteString("\t}\n")
	b.WriteString("\tvar dv string\n")
	b.WriteString("\tif err := json.Unmarshal(dvRaw, &dv); err != nil {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q, err)\n", "discriminator "+discJSON+" is not a string: %v")
	b.WriteString("\t}\n")
	// Reject unknown keys relative to the union's merged field set.
	b.WriteString("\tfor key := range raw {\n\t\tswitch key {\n")
	for _, f := range td.Fields {
		fmt.Fprintf(b, "\t\tcase %q:\n", f.JSONTag)
	}
	b.WriteString("\t\tdefault:\n\t\t\treturn fmt.Errorf(\"unknown field %q\", key)\n\t\t}\n\t}\n")
	// Discriminator must match a known const.
	fmt.Fprintf(b, "\ttype alias %s\n", td.Name)
	b.WriteString("\tif err := json.Unmarshal(data, (*alias)(u)); err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\tswitch %s(dv) {\n", enumName)
	enum := spec.Lookup(enumName)
	if enum != nil {
		for _, v := range enum.Values {
			fmt.Fprintf(b, "\tcase %s%s:\n", enumName, v.Name)
		}
		b.WriteString("\t\t// recognized discriminator value\n")
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q, dv)\n", "unknown discriminator "+discJSON+": %q")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}
