package structgen

import (
	"fmt"
	"strings"

	"github.com/umpire-tools/umpire-go-gen/pkg/codegen"
)

// Emission is the rendered Go source for a Spec.
type Emission struct {
	Source string
}

// EmitOptions configures structural emission.
type EmitOptions struct {
	PkgName      string // Go package name for the generated source
	SchemaName   string // camelCase/Pascal Go symbol prefix for the public raw API
	RootTypeName string // Go type that Decode<Schema> decodes into (e.g. <Schema>Fields)
}

// Emit writes a complete Go source file that uses only the standard library.
// It emits strict object decoders, enums, tagged unions, and typed validation.
// It also emits Validate<Schema>JSON, Decode<Schema>, and structural issue types.
// Profile-declared objects, unions, and enums never expose `any`.
func Emit(spec *Spec, opts EmitOptions) (*Emission, error) {
	utf8 := specNeedsImports(spec)

	var b strings.Builder
	b.WriteString("// Code generated by umpire-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.PkgName)
	emitImports(&b, utf8)

	// Plan-conformant raw validation + public API (Validate/Decode/StructuralIssue).
	emitStructural(&b, spec, opts)

	// Root object (with strict decode) + Validate().
	rootTD := TypeDef{Name: spec.RootName, Fields: spec.Root, Kind: KindObject}
	emitStruct(&b, spec.RootName, spec.Root)
	emitStrictDecode(&b, rootTD)
	emitValidation(&b, spec)

	// Enums, then objects, then unions.
	for _, td := range spec.Types {
		if td.Kind == KindEnum {
			emitEnum(&b, td)
		}
	}
	for _, td := range spec.Types {
		if td.Kind == KindObject {
			emitStruct(&b, td.Name, td.Fields)
			emitStrictDecode(&b, td)
		}
	}
	for _, td := range spec.Types {
		if td.Kind == KindUnion {
			emitStruct(&b, td.Name, td.Fields)
			emitUnionDecoder(&b, spec, td)
		}
	}

	return &Emission{Source: b.String()}, nil
}

func emitImports(b *strings.Builder, utf8 bool) {
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"strconv\"\n") // raw validator int parsing / array index paths
	b.WriteString("\t\"strings\"\n") // escapePtr + int parsing
	b.WriteString("\t\"sort\"\n")    // structural issue normalization
	if utf8 {
		b.WriteString("\t\"unicode/utf8\"\n")
	}
	b.WriteString(")\n\n")
}

// specNeedsImports reports whether utf8 (string code-point lengths) is required
// by the generated code. strconv, strings and sort are always emitted because
// the raw structural validator uses them unconditionally.
func specNeedsImports(spec *Spec) (utf8 bool) {
	walk := func(fields []FieldDef) {
		for _, f := range fields {
			switch f.Type.Kind {
			case KindScalar:
				if f.Type.Scalar == ScalarString && (f.MinLength != nil || f.MaxLength != nil) {
					utf8 = true
				}
			}
		}
	}
	walk(spec.Root)
	for _, td := range spec.Types {
		walk(td.Fields)
		for _, br := range td.Branches {
			walk(br.Fields)
		}
	}
	return
}

// RootGoTypes maps each original root property name to its Go type.
// Every profile root field uses a pointer to preserve presence.
// Nil records omission as distinct from an explicit value for Umpire evaluation.
func RootGoTypes(spec *Spec) map[string]string {
	out := make(map[string]string, len(spec.Root))
	for _, f := range spec.Root {
		out[f.Name] = "*" + baseGoType(f.Type)
	}
	return out
}

// baseGoType renders the non-nullable Go type string for a field type.
func baseGoType(ft FieldType) string {
	switch ft.Kind {
	case KindScalar:
		switch ft.Scalar {
		case ScalarString:
			return "string"
		case ScalarBool:
			return "bool"
		case ScalarInt:
			return "int64"
		case ScalarNumber:
			return "float64"
		}
	case KindArray:
		return "[]" + baseGoType(*ft.Elem)
	case KindObject, KindEnum, KindUnion:
		return ft.Ref
	}
	return "string"
}

// fieldGoType renders the nullable Go type for a field, honoring requiredness.
func fieldGoType(fd FieldDef) string {
	base := baseGoType(fd.Type)
	if fd.Required {
		return base
	}
	switch fd.Type.Kind {
	case KindScalar, KindObject, KindEnum, KindUnion:
		return "*" + base
	case KindArray:
		return base // nil slice already encodes absence
	}
	return base
}

// goJSONTag renders the struct tag for a field.
func goJSONTag(fd FieldDef) string {
	tag := fd.JSONTag
	if !fd.Required {
		tag += ",omitempty"
	}
	return tag
}

func emitStruct(b *strings.Builder, name string, fields []FieldDef) {
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, fd := range fields {
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", fd.GoName, fieldGoType(fd), goJSONTag(fd))
	}
	b.WriteString("}\n\n")
}

func emitEnum(b *strings.Builder, td TypeDef) {
	fmt.Fprintf(b, "type %s string\n\n", td.Name)
	b.WriteString("const (\n")
	for _, v := range td.Values {
		fmt.Fprintf(b, "\t%s%s %s = %q\n", td.Name, v.Name, td.Name, v.Wire)
	}
	b.WriteString(")\n\n")
}

// emitUnionDecoder renders a strict discriminator-based UnmarshalJSON for a union.
func emitUnionDecoder(b *strings.Builder, spec *Spec, td TypeDef) {
	discJSON := td.Discriminator
	enumName := td.Name + "Kind"

	fmt.Fprintf(b, "// UnmarshalJSON decodes %s by its %q discriminator const.\n", td.Name, discJSON)
	fmt.Fprintf(b, "func (u *%s) UnmarshalJSON(data []byte) error {\n", td.Name)
	b.WriteString("\tvar raw map[string]json.RawMessage\n")
	b.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\tdvRaw, ok := raw[%q]\n", discJSON)
	b.WriteString("\tif !ok {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q)\n", "missing discriminator field "+discJSON)
	b.WriteString("\t}\n")
	b.WriteString("\tvar dv string\n")
	b.WriteString("\tif err := json.Unmarshal(dvRaw, &dv); err != nil {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q, err)\n", "discriminator "+discJSON+" is not a string: %v")
	b.WriteString("\t}\n")
	// Dispatch per discriminator const. Each selected branch owns its property
	// set, so direct json.Unmarshal is strict too (not merely Decode's raw path).
	fmt.Fprintf(b, "\tswitch %s(dv) {\n", enumName)
	for _, br := range td.Branches {
		fmt.Fprintf(b, "\tcase %s%s:\n", enumName, codegen.GoFieldName(br.Wire))
		b.WriteString("\t\tfor key := range raw {\n\t\t\tswitch key {\n")
		for _, f := range br.Fields {
			fmt.Fprintf(b, "\t\t\tcase %q:\n", f.JSONTag)
		}
		b.WriteString("\t\t\tdefault:\n\t\t\t\treturn fmt.Errorf(\"unknown field %q\", key)\n\t\t\t}\n\t\t}\n")
		for _, req := range br.Required {
			if req == discJSON {
				continue
			}
			fmt.Fprintf(b, "\t\tif _, ok := raw[%q]; !ok {\n", req)
			fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(%q)\n", "branch \""+br.Wire+"\": missing required field \""+req+"\"")
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\tif %s {\n", "len(raw["+strconvQ(req)+"]) == 4 && string(raw["+strconvQ(req)+"]) == \"null\"")
			fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(%q)\n", "branch \""+br.Wire+"\": required field \""+req+"\" must not be null")
			b.WriteString("\t\t}\n")
		}
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(%q, dv)\n", "unknown discriminator "+discJSON+": %q")
	b.WriteString("\t}\n")
	// Decode via alias after validating the discriminator and branch requirements.
	fmt.Fprintf(b, "\ttype alias %s\n", td.Name)
	b.WriteString("\tif err := json.Unmarshal(data, (*alias)(u)); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}
